### ISSUE TITLE
The client application is not known or is not authorized.

### ISSUE THREAD

**Issue by kshetty** [scottbrady91/IdentityServer3-Example#1]
Hey Scott,

Just to let you know, when trying to sign in, we get a response as below:
"The client application is not known or is not authorized."

![image](https://cloud.githubusercontent.com/assets/6530390/7487014/7df82402-f3f2-11e4-8c73-4b685ca87254.png)

**Comment by scottbrady91** [comment]
Hi,

This error is received when your client is not in the list of redirect URI's (see the [Clients class](https://github.com/scottbrady91/IdentityServer3-Example/blob/master/src/ScottBrady91.IdentityServer3.Example/Configuration/Clients.cs)). Make sure that your client URL is in the appropriate list. 

As a side note, make sure to use your client's HTTPS URL and that it is set as your client's project URL.

If you're still experiencing this issue let me know.

Thanks,

Scott.

**Comment by kshetty** [comment]
Thanks for pointing that out. My bad!
I had downloaded the examples and changed the url's and expected everything to just work... 
Silly me! :smile:
