### ISSUE TITLE
Errors occurred while attempting to load the app

### ISSUE THREAD

**Issue by firasr** [scottbrady91/IdentityServer3-Example#2]
I got the following exception when loading the app for the first time:

**The following errors occurred while attempting to load the app.
The OwinStartupAttribute.FriendlyName value 'AspNetIdentity' does not match the given value 'Standard' in Assembly 'ScottBrady91.IdentityServer3.Example, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
The OwinStartupAttribute.FriendlyName value 'InMemory' does not match the given value 'Standard' in Assembly 'ScottBrady91.IdentityServer3.Example, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
The given type or method 'Standard' was not found. Try specifying the Assembly.
To disable OWIN startup discovery, add the appSetting owin:AutomaticAppStartup with a value of "false" in your web.config.
To specify the OWIN startup Assembly, Class, or Method, add the appSetting owin:AppStartup with the fully qualified startup class or configuration method name in your web.config.**

Suggest: I found that owin:AppStartup app setting value doesn't match what exists in Startup.cs.

Firas

**Comment by scottbrady91** [comment]
Good spot. Switched to `InMemory`
