### ISSUE TITLE
Signout does not work. FedAuth cookie is not cleared

### ISSUE THREAD

**Issue by codestellar** [scottbrady91/IdentityServer3-Example#3]
Hi,

I have implemented the sample in the same way and redirecting to signout as

`https://localhost:44309/identity/wsfed?wa=wsignout1.0&wreply=<myReplyUrl>&wtrealm=<myrealm>`
When this url is hit, I have been shown You are now logged out and I redirected back to my SharePoint website but the FedAuth cookie is not cleared.
I was having a CustomSecurityTokenService earlier and I want to use IdentityServer3 but signout is not working. Clearing the cookie should happen on IdentityServer3 side. Please note I am using Custom User Service and I have tried the following ways:

1. Tried Signout without overriding SignOutAsyncMethod of UserServiceBase

1. Overridden SignoutAsync method:

```
 FederationConfiguration cfg = FederatedAuthentication.FederationConfiguration;
      var fam = FederatedAuthentication.WSFederationAuthenticationModule;
        fam.SignOut(false);
        var signOutRequestMessage = new SignOutRequestMessage(new Uri(fam.Issuer), fam.Realm);

    return signOutRequestMessage.WriteQueryString();
```

1. Tried return base.SignOutAsync(context).;

All in vain. Can you please assist?

**Comment by scottbrady91** [comment]
FedAuth cookie is cleared by your SharePoint site, it has nothing to do with IdentityServer. You don't need to override any IdentityServer code to make it work with SharePoint.

If IdentityServer is clearing it's own cookies and the user is logged out of IdentityServer, then the fault is either within the configuration between SharePoint and IdentityServer, or within SharePoint.

**Comment by codestellar** [comment]
@scottbrady91 In that case there is no need to override SignOutAsync method? I was using a CustomSecurityTokenService earlier and to do the cleanup and was working like a charm:
`HttpCookie siteCookie = HttpContext.Current.Request.Cookies[SITECOOKIENAME];

    if (siteCookie != null)
        HttpContext.Current.Response.Cookies[SITECOOKIENAME].Expires = DateTime.Now.AddDays(-1);`

This does not work with IdentityServer3 WS-Fed.

**Comment by scottbrady91** [comment]
That's correct here's no need to do that.
